/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nhl_spindp_serialconn_SerialPort */

#ifndef _Included_com_nhl_spindp_serialconn_SerialPort
#define _Included_com_nhl_spindp_serialconn_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nhl_spindp_serialconn_SerialPort
 * Method:    initPort
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_nhl_spindp_serialconn_SerialPort_initPort
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_nhl_spindp_serialconn_SerialPort
 * Method:    cleanupPort
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_nhl_spindp_serialconn_SerialPort_cleanupPort
  (JNIEnv *, jobject);

/*
 * Class:     com_nhl_spindp_serialconn_SerialPort
 * Method:    nativeWrite
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_nhl_spindp_serialconn_SerialPort_nativeWrite
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_nhl_spindp_serialconn_SerialPort
 * Method:    nativeRead
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_nhl_spindp_serialconn_SerialPort_nativeRead
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_nhl_spindp_serialconn_SerialPort
 * Method:    nativeWriteBytes
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_nhl_spindp_serialconn_SerialPort_nativeWriteBytes
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_nhl_spindp_serialconn_SerialPort
 * Method:    nativeReadBytes
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_nhl_spindp_serialconn_SerialPort_nativeReadBytes
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
