/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nhl_spindp_bluetooth_BluetoothConnection */

#ifndef _Included_com_nhl_spindp_bluetooth_BluetoothConnection
#define _Included_com_nhl_spindp_bluetooth_BluetoothConnection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nhl_spindp_bluetooth_BluetoothConnection
 * Method:    setupBluetooth
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_nhl_spindp_bluetooth_BluetoothConnection_setupBluetooth
  (JNIEnv *, jobject);

/*
 * Class:     com_nhl_spindp_bluetooth_BluetoothConnection
 * Method:    connectionLoop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_nhl_spindp_bluetooth_BluetoothConnection_connectionLoop
  (JNIEnv *, jobject);

/*
 * Class:     com_nhl_spindp_bluetooth_BluetoothConnection
 * Method:    cleanupBluetooth
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_nhl_spindp_bluetooth_BluetoothConnection_cleanupBluetooth
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
