/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nhl_spindp_i2c_I2C */

#ifndef _Included_com_nhl_spindp_i2c_I2C
#define _Included_com_nhl_spindp_i2c_I2C
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nhl_spindp_i2c_I2C
 * Method:    initI2c
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_nhl_spindp_i2c_I2C_initI2c
  (JNIEnv *, jobject);

/*
 * Class:     com_nhl_spindp_i2c_I2C
 * Method:    i2cLoop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_nhl_spindp_i2c_I2C_i2cLoop
  (JNIEnv *, jobject);

/*
 * Class:     com_nhl_spindp_i2c_I2C
 * Method:    cleanupI2c
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_nhl_spindp_i2c_I2C_cleanupI2c
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
