/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nhl_spindp_Main */

#ifndef _Included_com_nhl_spindp_Main
#define _Included_com_nhl_spindp_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nhl_spindp_Main
 * Method:    isAlreadyRunning
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_nhl_spindp_Main_isAlreadyRunning
  (JNIEnv *, jclass);

/*
 * Class:     com_nhl_spindp_Main
 * Method:    cleanup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_nhl_spindp_Main_cleanup
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
